# .github/workflows/scrape-catalogs.yml
name: Scrape Catalogs

on:
  schedule:
    - cron: '0 0 */3 * *'  # Toutes les 72 heures
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install puppeteer axios

      - name: Run scraper
        run: node scraper.js
        
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update catalogs [automated]"
          git push
